CREATE TABLE IF NOT EXISTS videos (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  slug        VARCHAR(100) NOT NULL UNIQUE,
  img_src     VARCHAR(500) NOT NULL,
  tag         VARCHAR(50)  NOT NULL,
  title       VARCHAR(200) NOT NULL,
  views       VARCHAR(20)  NOT NULL DEFAULT '0',
  rating      VARCHAR(10)  DEFAULT NULL,
  likes       VARCHAR(20)  NOT NULL DEFAULT '0',
  comments    VARCHAR(20)  NOT NULL DEFAULT '0',
  shares      VARCHAR(20)  NOT NULL DEFAULT '0',
  bookmarks   VARCHAR(20)  NOT NULL DEFAULT '0',
  description TEXT         NOT NULL,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
